import type { AppsData } from "~/types";

const apps: AppsData[] = [
  {
    id: "bear",
    title: "About Me",
    desktop: true,
    width: 860,
    height: 540,
    minWidth: 640,
    minHeight: 400,
    x: 0,
    y: 0,
    img: "img/icons/bear.png",
    content: <Bear />,
  },
  {
    id: "mail",
    title: "Mail",
    desktop: true,
    width: 860,
    height: 540,
    minWidth: 640,
    minHeight: 400,
    x: 0,
    y: 0,
    img: "img/icons/mail.png",
    content: <Mail />,
  },
  // {
  //   id: "notes",
  //   title: "Notes",
  //   desktop: true,
  //   width: 860,
  //   height: 540,
  //   minWidth: 640,
  //   minHeight: 400,
  //   x: 0,
  //   y: 0,
  //   img: "img/icons/notes.png",
  //   content: <Notes />,
  // },
  {
    id: "system-settings",
    title: "System Settings",
    desktop: true,
    width: 860,
    height: 540,
    minWidth: 640,
    minHeight: 400,
    x: 0,
    y: 0,
    img: "img/icons/settings.png",
    content: <SystemSettings />,
  },
  {
    id: "github",
    title: "Github",
    desktop: false,
    img: "img/icons/github.png",
    link: "https://github.com/bntngjnrta",
  },
  {
    id: "linkedin",
    title: "LinkedIn",
    desktop: false,
    img: "img/icons/LinkedIn.png",
    link: "https://www.linkedin.com/in/kadek-bintang-januarta/",
  },
  {
    id: "Instagram",
    title: "Instagram",
    desktop: false,
    img: "img/icons/Instagram.png",
    link: "https://www.instagram.com/bntngjnrta?igsh=MW5kb3N4d2h6OW50bA==",
  },
];

export default apps;
